#Docfav Project

volumes:
    logs:
        driver: local

services:

    db-server:
        image: mysql:8.4.0
        restart: unless-stopped
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
        mem_limit: 1024m
        mem_reservation: 512M
        env_file:
            - ./docker/mysql/db-server.env
        ports:
            - 10003:3306
        volumes:
            - ./docker/mysql/root:/root
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/sql:/docker-entrypoint-initdb.d
        networks:
            - docfav-net
        healthcheck:
            test: mysql -h localhost -u root -e 'SELECT version();'
            start_period: 5s
            interval: 15s
            timeout: 5s
            retries: 5

    cache-server:
        image: redis:7.2.5-alpine
        #command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        restart: unless-stopped
        volumes:
            - ./docker/redis/root:/root
        ports:
            - "10002:6379"
        networks:
            - docfav-net

    app-backend:
        image: php:8.4-fpm
        mem_limit: 1024m
        mem_reservation: 512M
        build:
            context: ./docker/app-backend/
            dockerfile: dockerfile
        restart: unless-stopped
        working_dir: /var/www
        environment:
            docker: "true"
            REDIS_HOST: cache-server
        volumes:
            - ./docker/app-backend/root:/root
            - ./docker/app-backend/workers.conf:/etc/supervisor/conf.d/workers.conf
            - ./app-backend:/var/www
        networks:
            - docfav-net
        depends_on:
            - cache-server
            - db-server
        ports:
            - 10001:9001

    nginx:
        image: nginx:1.27.2-alpine
        build:
            context: ./docker/nginx/
            dockerfile: dockerfile
        restart: unless-stopped
        volumes:
            - ./docker/nginx/root:/root
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app-backend:/var/www/
        ports:
            - 10005:80
        networks:
            - docfav-net
        depends_on:
            - app-backend

networks:
    docfav-net:

